# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [3]:
import pandas as pd
import numpy as np

ccpfile = pd.read_csv("./data/ccp_current_csv.csv")
ccpfile

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [4]:
ccpfile.shape
# There are 465 rows  and 27 columns in the data

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [32]:
ccpfile['QUADRANT'].value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [41]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.add(a,b)


array([ 6,  8, 10, 12])

In [42]:
a+b

array([ 6,  8, 10, 12])

### 3.3.2 subtraction a-b

In [43]:
a-b

array([-4, -4, -4, -4])

In [44]:
np.subtract(a,b)

array([-4, -4, -4, -4])

### 3.3.3 multiplication a*b

In [45]:
a*b

array([ 5, 12, 21, 32])

In [46]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

### 3.3.4 divsion a/b

In [47]:
a/b

array([0, 0, 0, 0])

In [48]:
np.divide(a,b)

array([0, 0, 0, 0])

### 3.3.5 modulo  a%b

In [49]:
a%b

array([1, 2, 3, 4])

In [50]:
np.mod(a,b)

array([1, 2, 3, 4])

### 3.3.6 power  a^b

In [53]:
# ** gives power and ^ gives XOR of 2 arrays
a**b

array([    1,    64,  2187, 65536])

In [52]:
np.power(a,b)

array([    1,    64,  2187, 65536])

## Homework 3.4
Find your own data and load it into a dataframe

In [34]:
df = pd.read_csv("botnet")
df

No.          Time           Source        Destination Protocol  \
0              1      0.000000    60.190.223.75      147.32.84.165      TCP   
1              2      0.000168    60.190.223.75      147.32.84.165      TCP   
2              3      0.000377    147.32.84.165      60.190.223.75      TCP   
3              4      0.000384    147.32.84.165      60.190.223.75      TCP   
4              5      0.000629    60.190.223.75      147.32.84.165      TCP   
5              6      0.153526    147.32.84.165      60.190.223.75      TCP   
6              7      0.153540    147.32.84.165      60.190.223.75      TCP   
7              8      0.165282    60.190.223.75      147.32.84.165      TCP   
8              9      0.353897    147.32.84.165      60.190.223.75      TCP   
9             10      0.353907    147.32.84.165      60.190.223.75      TCP   
10            11      0.421743    60.190.223.75      147.32.84.165      TCP   
11            12      0.422075    147.32.84.165      60.190.223.75      TCP   
12            13      0.422084    147.32.84.165      60.190.223.75      TCP   
13            14      0.422094    60.190.223.75      147.32.84.165      TCP   
14            15      0.422216    147.32.84.165      60.190.223.75      TCP   
15            16      0.422223    147.32.84.165      60.190.223.75      TCP   
16            17      0.575786    60.190.223.75      147.32.84.165      TCP   
17            18      0.576005    147.32.84.165      60.190.223.75      TCP   
18            19      0.576014    147.32.84.165      60.190.223.75      TCP   
19            20      0.776044    60.190.223.75      147.32.84.165      TCP   
20            21      0.842866    60.190.223.75      147.32.84.165      TCP   
21            22      0.843101    147.32.84.165      60.190.223.75      TCP   
22            23      0.843115    147.32.84.165      60.190.223.75      TCP   
23            24      0.843207    60.190.223.75      147.32.84.165      TCP   
24            25      0.843269    60.190.223.75      147.32.84.165      TCP   
25            26      0.843334    147.32.84.165      60.190.223.75      TCP   
26            27      0.843341    147.32.84.165      60.190.223.75      TCP   
27            28      0.954856    147.32.84.165      60.190.223.75      TCP   
28            29      0.954870    147.32.84.165      60.190.223.75      TCP   
29            30      1.002401    60.190.223.75      147.32.84.165      TCP   
...          ...           ...              ...                ...      ...   
2129919  2129920   9966.870145    94.63.149.150      147.32.84.206      TCP   
2129920  2129921   9967.862830    94.63.149.150      147.32.84.206      TCP   
2129921  2129922   9968.086546    94.63.149.150      147.32.84.209      TCP   
2129922  2129923   9969.847183    94.63.149.150      147.32.84.206      TCP   
2129923  2129924   9973.817070    94.63.149.150      147.32.84.206      TCP   
2129924  2129925   9974.430366   83.133.119.197      147.32.84.204      TCP   
2129925  2129926   9976.151714   Cisco_db:19:c3          Broadcast      ARP   
2129926  2129927   9978.488210     50.7.244.234      147.32.84.206      TCP   
2129927  2129928   9980.892355  212.117.177.186      147.32.84.205      TCP   
2129928  2129929   9981.760088    94.63.149.150      147.32.84.206      TCP   
2129929  2129930   9984.470941      64.4.56.135      147.32.84.209      TCP   
2129930  2129931   9984.693746   Cisco_db:19:c3          Broadcast      ARP   
2129931  2129932   9985.271920    94.63.149.150      147.32.84.205      TCP   
2129932  2129933   9987.467013     50.7.244.234      147.32.84.206      TCP   
2129933  2129934   9989.424493   83.133.119.197      147.32.84.193      TCP   
2129934  2129935   9990.031117   Cisco_db:19:c3          Broadcast      ARP   
2129935  2129936   9990.070315  212.117.177.186      147.32.84.205      TCP   
2129936  2129937   9993.270284   Cisco_db:19:c3          Broadcast      ARP   
2129937  2129938   9993.875999   Cisco_db:19:c3          Broadc

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [35]:
df.shape

(2129949, 7)

In [36]:
df.size

14909643

In [37]:
df['Source'].unique()

array(['60.190.223.75', '147.32.84.165', '147.32.84.208', '147.32.80.9',
       '195.88.191.59', '113.70.243.53', '94.63.150.63', '122.224.6.164',
       '174.123.157.154', 'Cisco_db:19:c3', 'PcsCompu_e1:08:45',
       'PcsCompu_1f:65:4a', 'PcsCompu_a6:78:09', 'PcsCompu_54:b4:1b',
       'PcsCompu_72:52:25', 'PcsCompu_17:ba:94', 'PcsCompu_c3:c0:c5',
       'PcsCompu_eb:65:a9', 'PcsCompu_b5:b7:19', 'PcsCompu_e2:09:2d',
       '74.3.164.223', '61.147.99.179', '83.133.119.197', '85.130.81.228',
       '188.72.241.107', '91.220.0.52', '208.110.80.34', '117.213.61.195',
       '59.48.7.168', '119.154.71.9', '109.107.241.175', '178.123.14.199',
       '58.42.247.165', '212.117.171.138', '83.229.66.41',
       '125.166.97.131', '182.3.168.83', '202.112.126.218',
       '110.34.38.97', '204.12.208.59', '87.69.122.107', '87.247.53.237',
       '202.12.27.33', '193.0.14.129', '192.203.230.10', '173.192.170.88',
       '147.32.84.206', 'Dell_79:0a:65', '147.32.84.171', '91.220.0.54',
       '91.2

In [38]:
df.iloc[0]

No.                                                            1
Time                                                           0
Source                                             60.190.223.75
Destination                                        147.32.84.165
Protocol                                                     TCP
Length                                                      1514
Info           2012  >  1048 [ACK] Seq=1 Ack=1 Win=65434 Len=...
Name: 0, dtype: object

In [40]:
df['Time'].mean(axis=0)

5627.0574263543385

In [41]:
df['Source'].value_counts()

147.32.84.205      218497
147.32.84.208      197639
147.32.84.207      191162
147.32.84.209      164027
147.32.84.191      139857
147.32.84.193      134064
147.32.84.206      126127
147.32.84.192      125568
147.32.84.204      120007
147.32.84.165      118985
147.32.80.9        107989
195.113.232.81      64317
195.113.232.90      62760
212.117.177.186     44463
212.117.161.86      18718
46.4.36.120         16443
212.117.177.188     13599
50.7.244.234        12904
89.149.217.37       11907
65.55.196.251       10121
91.220.0.52          8634
173.192.170.88       8372
65.55.16.187         7794
212.117.171.138      7514
208.73.210.29        6778
64.4.56.135          6307
65.55.40.215         5773
204.12.234.66        4863
65.55.40.103         4213
65.55.33.167         3829
                    ...  
124.83.5.153            2
200.56.224.66           2
8.5.1.38                2
192.228.79.201          2
202.12.27.33            2
204.93.223.146          2
147.32.96.45            2
192.83.175.1

In [42]:
df['Source'].describe()

count           2129949
unique              869
top       147.32.84.205
freq             218497
Name: Source, dtype: object

In [43]:
df['Time'].max()

10002.548996

In [44]:
df['Time'].median()

5381.642192

In [45]:
df['Time'].mode()

0    4735.615907
1    4735.746928
dtype: float64